// <auto-generated />
using Gw2Tp.Infrastructure.Preferences;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gw2Tp.Infrastructure.Preferences.Migrations;

[DbContext(typeof(UserSessionPreferencesDbContext))]
[Migration("20260829120000_AddMarketScanPreferences")]
partial class AddMarketScanPreferences
{
}
