// <auto-generated />
using System;
using Gw2Tp.Infrastructure.Preferences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gw2Tp.Infrastructure.Preferences.Migrations
{
    [DbContext(typeof(UserSessionPreferencesDbContext))]
    [Migration("20260828120659_AddOperationActualOutcome")]
    partial class AddOperationActualOutcome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualOutcomeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Operations_Status", "Status IN ('planned', 'in-progress', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.ToTable("OperationScenarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperationScenarios_Kind", "Kind IN ('market-flip', 'crafting')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.UserSessionPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllocationPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CapitalLimitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumProfitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSessionPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSessionPreferences_AllocationPercent", "AllocationPercent BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_UserSessionPreferences_CapitalLimitCopper", "CapitalLimitCopper IS NULL OR (CapitalLimitCopper >= 0 AND CapitalLimitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_MinimumProfitCopper", "MinimumProfitCopper IS NULL OR (MinimumProfitCopper >= 0 AND MinimumProfitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_RiskPreference", "RiskPreference IN ('all', 'normal', 'reduced')");

                            t.HasCheckConstraint("CK_UserSessionPreferences_StrategyPreference", "StrategyPreference IN ('all', 'market-flip')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", b =>
                {
                    b.HasOne("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", "Operation")
                        .WithOne("Scenario")
                        .HasForeignKey("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", b =>
                {
                    b.Navigation("Scenario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
