// <auto-generated />
using System;
using Gw2Tp.Infrastructure.Preferences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gw2Tp.Infrastructure.Preferences.Migrations
{
    [DbContext(typeof(UserSessionPreferencesDbContext))]
    [Migration("20260828165005_AddMarketSnapshots")]
    partial class AddMarketSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketOrderBookLevelEntity", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Listings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPriceCopper")
                        .HasColumnType("INTEGER");

                    b.HasKey("SnapshotId", "Side", "Position");

                    b.ToTable("MarketOrderBookLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketOrderBookLevels_Listings", "Listings >= 0");

                            t.HasCheckConstraint("CK_MarketOrderBookLevels_Position", "Position >= 0");

                            t.HasCheckConstraint("CK_MarketOrderBookLevels_Quantity", "Quantity >= 0");

                            t.HasCheckConstraint("CK_MarketOrderBookLevels_Side", "Side IN ('buy', 'sell')");

                            t.HasCheckConstraint("CK_MarketOrderBookLevels_UnitPriceCopper", "UnitPriceCopper >= 0");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketOrderBookSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "CapturedAtUtcTicks", "Id");

                    b.ToTable("MarketOrderBookSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketOrderBookSnapshots_FormatVersion", "FormatVersion > 0");

                            t.HasCheckConstraint("CK_MarketOrderBookSnapshots_ItemId", "ItemId > 0");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketPriceSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BuyQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyUnitPriceCopper")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellUnitPriceCopper")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "CapturedAtUtcTicks", "Id");

                    b.ToTable("MarketPriceSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketPriceSnapshots_BuyQuantity", "BuyQuantity >= 0");

                            t.HasCheckConstraint("CK_MarketPriceSnapshots_BuyUnitPriceCopper", "BuyUnitPriceCopper >= 0");

                            t.HasCheckConstraint("CK_MarketPriceSnapshots_FormatVersion", "FormatVersion > 0");

                            t.HasCheckConstraint("CK_MarketPriceSnapshots_ItemId", "ItemId > 0");

                            t.HasCheckConstraint("CK_MarketPriceSnapshots_SellQuantity", "SellQuantity >= 0");

                            t.HasCheckConstraint("CK_MarketPriceSnapshots_SellUnitPriceCopper", "SellUnitPriceCopper >= 0");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketWatchlistItemEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamplingClass")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("MarketWatchlistItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_MarketWatchlistItems_ItemId", "ItemId > 0");

                            t.HasCheckConstraint("CK_MarketWatchlistItems_SamplingClass", "SamplingClass IN ('watchlist', 'background')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualOutcomeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationVersionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Operations_Status", "Status IN ('planned', 'in-progress', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId");

                    b.ToTable("OperationScenarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperationScenarios_Kind", "Kind IN ('market-flip', 'crafting')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.UserSessionPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllocationPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CapitalLimitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumProfitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSessionPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSessionPreferences_AllocationPercent", "AllocationPercent BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_UserSessionPreferences_CapitalLimitCopper", "CapitalLimitCopper IS NULL OR (CapitalLimitCopper >= 0 AND CapitalLimitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_MinimumProfitCopper", "MinimumProfitCopper IS NULL OR (MinimumProfitCopper >= 0 AND MinimumProfitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_RiskPreference", "RiskPreference IN ('all', 'normal', 'reduced')");

                            t.HasCheckConstraint("CK_UserSessionPreferences_StrategyPreference", "StrategyPreference IN ('all', 'market-flip')");
                        });
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketOrderBookLevelEntity", b =>
                {
                    b.HasOne("Gw2Tp.Infrastructure.Preferences.MarketOrderBookSnapshotEntity", "Snapshot")
                        .WithMany("Levels")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", b =>
                {
                    b.HasOne("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", "Operation")
                        .WithOne("Scenario")
                        .HasForeignKey("Gw2Tp.Infrastructure.Preferences.OperationHistoryScenarioEntity", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.MarketOrderBookSnapshotEntity", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.OperationHistoryEntity", b =>
                {
                    b.Navigation("Scenario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
