// <auto-generated />
using Gw2Tp.Infrastructure.Preferences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gw2Tp.Infrastructure.Preferences.Migrations
{
    [DbContext(typeof(UserSessionPreferencesDbContext))]
    partial class UserSessionPreferencesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Gw2Tp.Infrastructure.Preferences.UserSessionPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllocationPercent")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CapitalLimitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumProfitCopper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RiskPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSessionPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSessionPreferences_AllocationPercent", "AllocationPercent BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_UserSessionPreferences_CapitalLimitCopper", "CapitalLimitCopper IS NULL OR (CapitalLimitCopper >= 0 AND CapitalLimitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_MinimumProfitCopper", "MinimumProfitCopper IS NULL OR (MinimumProfitCopper >= 0 AND MinimumProfitCopper <= 9007199254740991)");

                            t.HasCheckConstraint("CK_UserSessionPreferences_RiskPreference", "RiskPreference IN ('all', 'normal', 'reduced')");

                            t.HasCheckConstraint("CK_UserSessionPreferences_StrategyPreference", "StrategyPreference IN ('all', 'market-flip')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
