import { type ReactNode, useMemo } from 'react';
import MoneyDisplay from './MoneyDisplay';
import { useViewQuery } from './viewQueryCache';

type Money = { copper: string };
type Explanation = {
  version: number;
  state: 'ready' | 'unavailable';
  reason?: string;
  theory: { positionSizing: { version: number; basisPointsPerWhole: number; reserveRounding: string; capRounding: string; purchaseOnly: boolean }; fees: { version: number; listingFeeBasisPoints: number; exchangeFeeBasisPoints: number; minimumPositiveFeeCopper: string; rounding: string; fractionalCopperRoundingExternallyVerified: boolean; verification: string }; crafting: { missingInputPolicy: string; listingIdentifierPolicy: string } };
  current: null | { generatedAtUtc: string | null; cachedAtUtc: string; expiresAtUtc: string | null; policy: { cashReserveBasisPoints: number; positionSizingVersion: number; feeVersion: number; fifoVersion: number; minimumProfitCopper: string; minimumRoiBasisPoints: number }; capitalState: string; capital: null | { availableCash: Money; totalBankroll: Money; cashReserve: Money; reserveStatus: string; reserveShortfall: Money; remainingCashAfterSizing: Money; evidenceState: string; exposures: Array<{ kind: string; itemId: number; strategy: string; category: string; capital: Money }> }; sources: { account: Source; orders: Source; market: Source; crafting: Source } };
  actions: ActionExplanation[];
  plans?: Array<{ id: string; state: string; currentStepOrdinal: number; candidate: CandidateTrace | null }>;
  craftingCandidates?: CraftingExplanation[];
  crafting?: { state: string; evidenceFailureCode: string | null; summaryExclusions: string[]; truncationReasons: string[] };
  selection: { generatedCandidates: number; hardEligibleCandidates: number; resourceEligibleCandidates: number; selectedCandidates: number; portfolioSizingUnavailable?: boolean; unavailableReason?: string | null; resources?: ResourceTrace | null };
};
type Source = { state: string; observedAtUtc: string | null; expiresAtUtc: string | null };
type ActionExplanation = { id: string; action: string; itemId: number; itemName: string; quantity: number; executableSignal: boolean; excludedFromSelection: boolean; capital: Money; economics: null | { acquisitionCost: Money; grossSaleValue: Money; listingFee: Money; exchangeFee: Money; netSaleProceeds: Money; netProfit: Money; totalCost: Money; roiDisplayPercent: string; acquisitionBasisState: string }; constraints: Array<{ name: string; capitalCapacity: Money; quantityCapacity: number; isBinding: boolean }>; reasons: Array<{ code: string }>; evidence: { historyObservedAtUtc: string | null; historyState: string; liquidityState: string } };
type CandidateTrace = { id: string | null; isHardEligible: boolean; utility: number; modeledProfit: Money; committedCapital: Money; selected: boolean; excludedFromSelection: boolean; exclusions: string[]; requirements: Array<{ kind: string; quantity: number; cash: Money }>; selection?: { stage: string; reason: string } | null };
type ResourceTrace = { effectiveCash: Money; reservedCash: Money; availableCash: Money; hardReserve: Money; reservations: Array<{ kind: string; itemId: number | null; quantity: number; cash: Money }>; availableVerifiedInventory: Array<{ itemId: number | null; quantity: number }> };
type CraftingExplanation = { id: string; outputItemId: number; outputName: string; state: string; isActionable: boolean; exclusions: string[]; candidate: CandidateTrace | null; economics: { economicInputCost: Money | null; outputSale: { grossSaleValue: Money; listingFee: Money; exchangeFee: Money; netSaleProceeds: Money } | null; netProfit: Money | null; totalCost: Money | null; roiBasisPoints: string | null; uncertainties: string[]; ingredients: IngredientExplanation[] } };
type IngredientExplanation = { itemId: number; requiredQuantity: number; ownedTradableQuantity: number; boundQuantity: number; unknownQuantity: number; purchasedQuantity: number; strategy: string; ownedOpportunityCost: Money | null; purchasedAcquisitionCost: Money | null; economicInputCost: Money | null; uncertainties: string[]; acquisition: { strategy: string; quantity: number; totalCost: Money; execution: { requestedQuantity: number; filledQuantity: number; isFullyFilled: boolean; totalValue: Money } | null } | null; acquisitionAlternatives: Array<{ strategy: string; quantity: number; totalCost: Money | null; execution: { requestedQuantity: number; filledQuantity: number; isFullyFilled: boolean; totalValue: Money } | null }> };

const headers = { Accept: 'application/json', 'X-Tyrian-Ledger-Request': '1' };

export default function CalculationTransparencyPanel({ focus }: { focus: string | null }) {
  const query = useViewQuery(useMemo(() => ({ key: 'calculation-explanations', url: '/api/calculation-explanations', init: { headers }, validate: isExplanation, discardOnError: true }), []));
  const value = query.data;
  const focused = focus === null ? null : value?.actions.find(action => action.id === focus) ?? null;
  const focusedPlan = focus === null ? null : value?.plans?.find(plan => plan.id === focus) ?? null;
  const focusedCraft = focus === null ? null : value?.craftingCandidates?.find(candidate => candidate.id === focus) ?? null;

  return <section aria-labelledby="calculation-transparency-title" className="settings-panel calculation-transparency">
    <div className="settings-panel-heading"><div><h2 id="calculation-transparency-title">Comprendre mes calculs</h2><p className="settings-section-note">Règles versionnées et preuves utilisées par le dernier cycle de décision.</p></div><button onClick={() => query.refresh()} type="button">Actualiser l'explication</button></div>
    {query.phase === 'loading' && <p role="status">Lecture de l'explication du dernier calcul…</p>}
    {query.phase === 'error' && <p className="operational-status operational-status--warning" role="status">L'explication n'est pas disponible pour le moment. Les données de décision ne sont pas relancées automatiquement.</p>}
    {value?.state === 'unavailable' && <p className="operational-status operational-status--warning" role="status">Les valeurs actuelles ont expiré ou n'appartiennent plus au compte actif. Synchronisez, puis ouvrez à nouveau l'explication.</p>}
    {value?.state === 'ready' && value.current && <>
      <p className="calculation-meta">Cycle calculé le {formatDate(value.current.generatedAtUtc)} · valable jusqu'au {formatDate(value.current.expiresAtUtc)} · politique de dimensionnement v{value.current.policy.positionSizingVersion}, frais v{value.current.policy.feeVersion}.</p>
      {(focused || focusedPlan || focusedCraft) && <aside className="calculation-focus" aria-live="polite"><strong>Contexte ouvert : {focused?.itemName ?? (focusedPlan ? 'Plan en cours' : focusedCraft?.outputName)}</strong><span>{focused ? (focused.executableSignal ? 'Ce signal est exécutable dans la sélection actuelle.' : focused.excludedFromSelection ? 'Ce candidat est écarté par la sélection actuelle.' : 'Cette observation est consultable mais ne forme pas un signal exécutable.') : focusedPlan ? `État du plan : ${planStateLabel(focusedPlan.state)}.` : 'Ce parcours utilise les preuves d’artisanat du même cycle de décision.'}</span>{(focusedPlan?.candidate || focusedCraft?.candidate) && <CandidateLineage candidate={focusedPlan?.candidate ?? focusedCraft!.candidate!} />}{focusedCraft && <CraftingEvidence craft={focusedCraft} />}</aside>}
      <details open><summary>Capital et limites</summary><div className="calculation-grid"><Rule title="Comment ça marche"><p>La réserve est arrondie vers le haut ; les plafonds d'item, de stratégie et de catégorie sont arrondis vers le bas. Ces contraintes dimensionnent uniquement un nouvel achat.</p></Rule><Evidence title="Avec mes données">{value.current.capital ? <><MoneyLine label="Liquidités vérifiées" value={value.current.capital.availableCash} /><MoneyLine label="Capital total" value={value.current.capital.totalBankroll} /><MoneyLine label="Réserve" value={value.current.capital.cashReserve} /><MoneyLine label="Disponible après allocations" value={value.current.capital.remainingCashAfterSizing} /><p>Réserve : {reserveLabel(value.current.capital.reserveStatus)}.</p>{value.current.capital.exposures?.map((exposure, index) => <MoneyLine key={`${exposure.kind}-${index}`} label={`Exposition ${exposureLabel(exposure.kind)}`} value={exposure.capital} />)}{value.selection.resources && <ResourceEvidence resources={value.selection.resources} />}</> : <p>{value.current.capitalState === 'purchase_sizing_unavailable' ? 'Le dimensionnement des achats est indisponible car la base du portefeuille ne peut pas être établie de façon sûre.' : "Le portefeuille n'est pas suffisamment connu pour dimensionner un achat."} Une vente de stock détenu conserve ses propres preuves et ne reçoit pas cette contrainte d'achat.</p>}</Evidence></div></details>
      <details><summary>Prix, frais et profit</summary><div className="calculation-grid"><Rule title="Comment ça marche"><p>Le modèle applique séparément {percent(value.theory.fees.listingFeeBasisPoints)} de frais de mise en vente et {percent(value.theory.fees.exchangeFeeBasisPoints)} de frais d'échange, chacun avec un minimum de {value.theory.fees.minimumPositiveFeeCopper} cuivre et {roundingLabel(value.theory.fees.rounding)}. L'arrondi fractionnaire reste une hypothèse documentée ({value.theory.fees.verification}).</p></Rule><Evidence title="Avec mes données">{focused?.economics ? <Economics economics={focused.economics} /> : <p>Sélectionnez « Pourquoi ? » depuis un signal pour afficher ses montants exacts. Un coût d'acquisition inconnu reste inconnu.</p>}</Evidence></div></details>
      <details><summary>Artisanat</summary><div className="calculation-grid"><Rule title="Comment ça marche"><p>Les matériaux possédés sont valorisés à leur coût d'opportunité. Un prix, une profondeur, une recette ou un identifiant de listing manquant ne devient jamais un prix nul.</p></Rule><Evidence title="Avec mes données">{focusedCraft ? <CraftingEvidence craft={focusedCraft} /> : <p>Ouvrez « Pourquoi ? » depuis un parcours d’artisanat pour voir ingrédients, alternatives d’approvisionnement et preuves disponibles.</p>}{value.crafting?.evidenceFailureCode && <p>Preuve globale indisponible : {craftingFailureLabel(value.crafting.evidenceFailureCode)}. Actualisez les données d’artisanat avant d’attribuer ce manque à un ingrédient précis.</p>}<p>Incertitudes suivies : {value.theory.crafting.listingIdentifierPolicy} et coûts d'entrée inconnus.</p></Evidence></div></details>
      <details><summary>Signaux et Plans</summary><div className="calculation-grid"><Rule title="Comment ça marche"><p>Une recommandation observée devient un signal seulement après les contraintes strictes, les ressources et la sélection déterministe de plans compatibles. Une notification requiert en plus un signal exécutable.</p></Rule><Evidence title="Avec mes données"><p>{value.selection.generatedCandidates} candidat{plural(value.selection.generatedCandidates)} généré{plural(value.selection.generatedCandidates)} · {value.selection.hardEligibleCandidates} après contraintes strictes · {value.selection.resourceEligibleCandidates} après ressources · {value.selection.selectedCandidates} sélectionné{plural(value.selection.selectedCandidates)}.</p>{focused && <><p>Décision : {focused.executableSignal ? 'signal sélectionné' : focused.excludedFromSelection ? 'candidat rejeté lors de la sélection' : 'observation non sélectionnée'}.</p><ul>{focused.reasons.map(reason => <li key={reason.code}>{reasonLabel(reason.code)}</li>)}</ul>{focused.constraints.filter(constraint => constraint.isBinding).map(constraint => <p key={constraint.name}>Limite active : {constraintLabel(constraint.name)} ({constraint.quantityCapacity} unité{plural(constraint.quantityCapacity)}).</p>)}</>}</Evidence></div></details>
      <details><summary>Fiabilité des données</summary><div className="calculation-grid"><Rule title="Comment ça marche"><p>Chaque source est affichée avec son horodatage. Après l'expiration, elle n'est plus présentée comme exécutable. Le navigateur ne reçoit ni clé ArenaNet, ni identifiant de compte, ni diagnostic brut.</p></Rule><Evidence title="Avec mes données"><SourceLine label="Compte" value={value.current.sources.account} /><SourceLine label="Ordres" value={value.current.sources.orders} /><SourceLine label="Marché" value={value.current.sources.market} /><SourceLine label="Artisanat" value={value.current.sources.crafting} /></Evidence></div></details>
    </>}
  </section>;
}

function Rule({ title, children }: { title: string; children: ReactNode }) { return <section><h3>{title}</h3>{children}</section>; }
function Evidence({ title, children }: { title: string; children: ReactNode }) { return <section><h3>{title}</h3>{children}</section>; }
function MoneyLine({ label, value }: { label: string; value: Money }) { return <p className="calculation-money"><span>{label}</span><MoneyDisplay compact money={value} /></p>; }
function Economics({ economics }: { economics: NonNullable<ActionExplanation['economics']> }) { return <><MoneyLine label="Coût d'acquisition" value={economics.acquisitionCost} /><MoneyLine label="Vente brute" value={economics.grossSaleValue} /><MoneyLine label="Frais de mise en vente" value={economics.listingFee} /><MoneyLine label="Frais d'échange" value={economics.exchangeFee} /><MoneyLine label="Produit net" value={economics.netSaleProceeds} /><MoneyLine label="Profit modélisé" value={economics.netProfit} /><p>ROI : {economics.roiDisplayPercent}. Base d'acquisition : {economics.acquisitionBasisState === 'known' ? 'connue' : 'inconnue'}.</p></>; }
function CandidateLineage({ candidate }: { candidate: CandidateTrace }) { return <><p>Candidate : {candidate.isHardEligible ? 'contraintes strictes satisfaites' : 'contraintes strictes non satisfaites'} · utilité {candidate.utility} · {candidate.selected ? 'sélectionné' : candidate.excludedFromSelection ? 'écarté à la sélection' : 'non sélectionné'}.</p>{candidate.selection && <p>Étape bloquante : {selectionStageLabel(candidate.selection.stage)}.</p>}<MoneyLine label="Capital du candidat" value={candidate.committedCapital} /><MoneyLine label="Profit modélisé" value={candidate.modeledProfit} />{candidate.requirements.map((requirement, index) => <p key={`${requirement.kind}-${index}`}>Ressource requise : {resourceLabel(requirement.kind)} · {requirement.quantity} unité{plural(requirement.quantity)} · <MoneyDisplay compact money={requirement.cash} />.</p>)}{candidate.exclusions.map(exclusion => <p key={exclusion}>Exclusion : {exclusion}.</p>)}</>; }
function ResourceEvidence({ resources }: { resources: ResourceTrace }) { return <><MoneyLine label="Liquidités effectives" value={resources.effectiveCash} /><MoneyLine label="Liquidités réservées par les Plans" value={resources.reservedCash} /><MoneyLine label="Liquidités disponibles pour la sélection" value={resources.availableCash} /><MoneyLine label="Réserve bloquante" value={resources.hardReserve} />{resources.reservations.map((reservation, index) => <p key={`${reservation.kind}-${reservation.itemId ?? 'global'}-${index}`}>Réservation : {resourceLabel(reservation.kind)}{reservation.itemId ? ` · objet ${reservation.itemId}` : ''} · {reservation.quantity} unité{plural(reservation.quantity)} · <MoneyDisplay compact money={reservation.cash} />.</p>)}</>; }
function CraftingEvidence({ craft }: { craft: CraftingExplanation }) { return <div><p>État économique : {craftingStateLabel(craft.state)}. {craft.isActionable ? 'Le parcours est actionnable.' : 'Le parcours est exclu tant que les preuves sont incomplètes ou défavorables.'}</p>{craft.economics.economicInputCost ? <MoneyLine label="Coût économique des entrées" value={craft.economics.economicInputCost} /> : <p>Le coût économique total reste inconnu : il n’est pas remplacé par zéro.</p>}{craft.economics.outputSale && <><MoneyLine label="Produit net de sortie" value={craft.economics.outputSale.netSaleProceeds} />{craft.economics.netProfit && <MoneyLine label="Profit modélisé" value={craft.economics.netProfit} />}</>}{craft.economics.ingredients.map(ingredient => <details key={ingredient.itemId}><summary>Ingrédient {ingredient.itemId} · {ingredient.requiredQuantity} requis</summary><p>Possédé échangeable : {ingredient.ownedTradableQuantity} · lié : {ingredient.boundQuantity} · inconnu : {ingredient.unknownQuantity} · à acquérir : {ingredient.purchasedQuantity}.</p>{ingredient.ownedOpportunityCost && <MoneyLine label="Coût d’opportunité possédé" value={ingredient.ownedOpportunityCost} />}{ingredient.acquisition ? <><p>Parcours retenu : {acquisitionLabel(ingredient.acquisition.strategy)} ({ingredient.acquisition.quantity}).</p><MoneyLine label="Coût d’acquisition" value={ingredient.acquisition.totalCost} />{ingredient.acquisition.execution && <p>Profondeur : {ingredient.acquisition.execution.filledQuantity}/{ingredient.acquisition.execution.requestedQuantity} unités couvertes.</p>}</> : <p>Aucun parcours d’acquisition complet n’est disponible.</p>}{ingredient.acquisitionAlternatives.length > 1 && <p>Alternatives évaluées : {ingredient.acquisitionAlternatives.map(alternative => `${acquisitionLabel(alternative.strategy)}${alternative.totalCost ? ` (${alternative.totalCost.copper} cuivre)` : ' (coût inconnu)'}`).join(' · ')}.</p>}{ingredient.uncertainties.map(value => <p key={value}>Preuve manquante : {uncertaintyLabel(value)}.</p>)}</details>)}</div>; }
function SourceLine({ label, value }: { label: string; value: Source }) { return <p><strong>{label}</strong> : {value.state === 'known' ? `observé le ${formatDate(value.observedAtUtc)}` : 'inconnu ou indisponible'}.</p>; }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleString('fr-FR') : 'inconnu'; }
function plural(value: number) { return value === 1 ? '' : 's'; }
function reserveLabel(value: string) { return value === 'Satisfied' ? 'respectée' : 'à restaurer'; }
function exposureLabel(value: string) { return ({ CurrentBuyOrder: 'ordre d’achat en cours', HeldPosition: 'position détenue' } as Record<string, string>)[value] ?? 'existante'; }
function craftingStateLabel(value: string) { return ({ Available: 'complet', Incomplete: 'incomplet' } as Record<string, string>)[value] ?? 'inconnu'; }
function craftingFailureLabel(value: string) { return ({ market_listings_unavailable: 'les listings de marché n’ont pas pu être lus', market_metadata_unavailable: 'les métadonnées de marché n’ont pas pu être lues', recipe_definitions_unavailable: 'les recettes nécessaires n’ont pas pu être lues' } as Record<string, string>)[value] ?? 'la source nécessaire à la recherche limitée n’est pas disponible'; }
function acquisitionLabel(value: string) { return ({ InstantBuy: 'achat immédiat', BuyOrder: 'ordre d’achat', CraftedIntermediate: 'intermédiaire fabriqué' } as Record<string, string>)[value] ?? 'inconnu'; }
function uncertaintyLabel(value: string) { return ({ BoundOwnedInput: 'matériau lié', UnknownOwnedInput: 'quantité possédée inconnue', OpportunityPriceUnavailable: 'prix d’opportunité indisponible', AcquisitionPriceUnavailable: 'prix ou profondeur d’acquisition indisponible', OutputPriceUnavailable: 'prix de sortie indisponible', InsufficientMarketDepth: 'profondeur de marché insuffisante' } as Record<string, string>)[value] ?? 'preuve économique indisponible'; }
function resourceLabel(value: string) { return ({ Cash: 'liquidités', Inventory: 'inventaire vérifié', OpenOrderExposure: 'ordre existant', Position: 'position', ExpectedIncoming: 'entrée attendue' } as Record<string, string>)[value] ?? 'ressource'; }
function selectionStageLabel(value: string) { return ({ selected: 'sélectionné', purchase_sizing_unavailable: 'dimensionnement d’achat indisponible', hard_constraint_rejected: 'contrainte stricte non satisfaite', no_verified_inventory: 'inventaire vérifié absent', insufficient_verified_inventory: 'quantité vérifiée insuffisante', inventory_reserved: 'inventaire déjà réservé par un Plan', generic_resource_conflict: 'conflit avec une ressource générique réservée', insufficient_cash_or_listing_fee_capacity: 'liquidités ou frais de mise en vente insuffisants après réserve', negative_utility_empty_bundle: 'utilité négative : le panier vide est préférable', selection_rejected: 'non retenu par la sélection déterministe' } as Record<string, string>)[value] ?? 'contrainte de sélection'; }
function constraintLabel(value: string) { return ({ CashAfterReserve: 'liquidités après réserve', ItemExposure: "plafond de l'objet", LiquidityParticipation: 'profondeur de marché', StrategyConcentration: 'concentration de stratégie', CategoryConcentration: 'concentration de catégorie' } as Record<string, string>)[value] ?? 'contrainte de portefeuille'; }
function reasonLabel(value: string) { return ({ StrongEvidence: 'Les preuves disponibles satisfont le seuil de décision.', NoSizingCapacity: 'Le dimensionnement sûr ne laisse aucune capacité.', EvidenceMissing: 'Une preuve nécessaire manque ou a expiré.', UnknownCostBasis: "Le coût d'acquisition historique reste inconnu.", ItemExposureExceeded: "Le plafond de l'objet est atteint.", StrategyExposureExceeded: 'Le plafond de stratégie est atteint.', CategoryExposureExceeded: 'Le plafond de catégorie est atteint.', LiquidityRisk: 'La liquidité ne satisfait pas les contraintes.' } as Record<string, string>)[value] ?? 'Cette règle a influencé la décision.'; }
function planStateLabel(value: string) { return ({ InProgress: 'en cours', RecheckRequired: 'à recalculer', ReconciliationRequired: 'à réconcilier', Waiting: 'en attente' } as Record<string, string>)[value] ?? 'à vérifier'; }
function percent(basisPoints: number) { return new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 }).format(basisPoints / 100) + ' %'; }
function roundingLabel(value: string) { return value === 'up_independently' ? 'un arrondi indépendant vers le haut' : 'la règle d’arrondi fournie par la politique'; }
function isExplanation(value: unknown): value is Explanation { return typeof value === 'object' && value !== null && 'version' in value && 'state' in value && (value as { version: unknown }).version === 1 && ((value as { state: unknown }).state === 'ready' || (value as { state: unknown }).state === 'unavailable'); }
